program: sweep_inference.py
method: grid
metric:
  name: panoptic_seg/PQ
  goal: maximize

parameters:
  object_thr:
    values: [0.0, 0.15, 0.20, 0.25, 0.30]

  overlap_thr:
    values: [0.6, 0.7, 0.8, 0.9] 