program: sweep_train.py
method: bayes
metric:
  name: panoptic_seg/PQ
  goal: maximize

parameters:
  # ──────────────── LR & warm-up ────────────────
  base_lr:
    distribution: log_uniform_values
    min: 0.00003 # 3e-5
    max: 0.0003 # 3e-4

  warmup_iters:
    distribution: uniform
    min: 500
    max: 2000
  warmup_factor:
    values: [0.001, 0.01, 0.1, 1.0]

  # ──────────────── Regularisation ────────────────
  weight_decay:
    values: [1e-5, 2e-5, 5e-5, 1e-4]
  grad_clip_value:
    values: [0.01, 0.02, 0.05]

  # ────────────── Loss balancing ────────────────
  dice_weight:
    values: [3.0, 5.0, 7.0, 10.0]
  mask_weight:
    values: [3.0, 5.0, 7.0, 10.0]
  class_weight:
    values: [1.0, 2.0, 3.0]

  # ─────── Training length (fixed) ───────
  max_iter:
    value: 10000

  # ─────── Backbone multiplier ───────
  backbone_multiplier:
    values: [0.05, 0.1, 0.2] 